"""
Django settings for barpilote project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}


# Development remains convenient; production values live only in the VPS .env.
DEBUG = _env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-development-only-change-me')
if not DEBUG and SECRET_KEY == 'django-insecure-development-only-change-me':
    raise RuntimeError('DJANGO_SECRET_KEY must be configured when DJANGO_DEBUG=false')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]

SITE_URL = os.environ.get('SITE_URL', 'https://www.barpilote.com').rstrip('/')
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'proprietaire',
    'serveur',  # Nouvelle application serveur
    'client',
    'authentification',
    
    # Auth & API
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'proprietaire.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'proprietaire.middleware.SessionManagementMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'proprietaire.middleware.RoleRouteAccessMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# CORS Config
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]

# Auth settings (Allauth)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL = '/auth/login/redirect/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/auth/login/'

# Email login codes. In development, Django falls back to console output unless SMTP
# credentials are present in .env.
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in {'1', 'true', 'yes', 'on'}
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@barpilote.local')
DEVELOPER_CONTACT_EMAIL = os.environ.get('DEVELOPER_CONTACT_EMAIL', 'barpilote2026@mail.com')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD else 'django.core.mail.backends.console.EmailBackend',
)


REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'barpilote-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'barpilote-refresh-token',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

ROOT_URLCONF = 'barpilote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'proprietaire.context_processors.currency_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'barpilote.wsgi.application'
ASGI_APPLICATION = 'barpilote.asgi.application'
    
# Session Settings
SESSION_COOKIE_AGE = 86400 * 30  # 30 jours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        },
    }
}

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 heures
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Configuration avancée des sessions
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
# Nettoyage automatique des sessions expirées
SESSION_COOKIE_DOMAIN = None

CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth additional settings
SOCIALACCOUNT_ADAPTER = 'authentification.adapters.SocialAccountAdapter'
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Création automatique du User lors du premier login social
SOCIALACCOUNT_LOGIN_ON_GET = True  # Rediriger immédiatement vers Google sans page intermédiaire
ACCOUNT_SESSION_REMEMBER = True  # Garder la session active par défaut
ACCOUNT_LOGOUT_ON_GET = True  # Déconnexion immédiate sans page de confirmation

# Google Maps Configuration
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')


# AI Advisor Configuration
AI_ADVISOR_PROVIDER = os.environ.get('AI_ADVISOR_PROVIDER', 'local').lower()
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.0-flash')
GEMINI_REQUEST_TIMEOUT = int(os.environ.get('GEMINI_REQUEST_TIMEOUT', '20'))
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-5.5')
OPENAI_REQUEST_TIMEOUT = int(os.environ.get('OPENAI_REQUEST_TIMEOUT', '20'))

# Google AdSense. Renseigner GOOGLE_ADSENSE_CLIENT_ID au format ca-pub-xxxxxxxxxxxxxxxx
# et un slot par audience pour afficher de vraies publicites Google pendant l'essai gratuit.
GOOGLE_ADSENSE_CLIENT_ID = os.environ.get('GOOGLE_ADSENSE_CLIENT_ID', '')
GOOGLE_ADSENSE_SLOT_OWNER = os.environ.get('GOOGLE_ADSENSE_SLOT_OWNER', '')
GOOGLE_ADSENSE_SLOT_SERVER = os.environ.get('GOOGLE_ADSENSE_SLOT_SERVER', '')
GOOGLE_ADSENSE_SLOT_CLIENT = os.environ.get('GOOGLE_ADSENSE_SLOT_CLIENT', '')
GOOGLE_ADSENSE_SELLER_ID = os.environ.get('GOOGLE_ADSENSE_SELLER_ID', 'f08c47fec0942fa0')


# Realtime / Push notifications
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

FCM_SERVICE_ACCOUNT_FILE = os.environ.get('FCM_SERVICE_ACCOUNT_FILE', '')
FCM_SERVICE_ACCOUNT_JSON = os.environ.get('FCM_SERVICE_ACCOUNT_JSON', '')
FCM_WEB_API_KEY = os.environ.get('FCM_WEB_API_KEY', '')
FCM_WEB_AUTH_DOMAIN = os.environ.get('FCM_WEB_AUTH_DOMAIN', '')
FCM_WEB_PROJECT_ID = os.environ.get('FCM_WEB_PROJECT_ID', '')
FCM_WEB_STORAGE_BUCKET = os.environ.get('FCM_WEB_STORAGE_BUCKET', '')
FCM_WEB_MESSAGING_SENDER_ID = os.environ.get('FCM_WEB_MESSAGING_SENDER_ID', '')
FCM_WEB_APP_ID = os.environ.get('FCM_WEB_APP_ID', '')
FCM_WEB_VAPID_KEY = os.environ.get('FCM_WEB_VAPID_KEY', '')

# Google AdSense Reporting API (OAuth read-only)
ADSENSE_ACCOUNT_ID = os.environ.get('ADSENSE_ACCOUNT_ID', '')
ADSENSE_REFRESH_TOKEN = os.environ.get('ADSENSE_REFRESH_TOKEN', '')
GOOGLE_ADSENSE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_ADSENSE_OAUTH_CLIENT_ID', os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''))
GOOGLE_ADSENSE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_ADSENSE_OAUTH_CLIENT_SECRET', os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''))
