# Generated by Django 6.0.4 on 2026-06-16 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaire', '0032_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrderMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('client_postnom', models.CharField(blank=True, max_length=120)),
                ('client_prenom', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20)),
                ('debt_requested', models.BooleanField(default=False)),
                ('debt_reason', models.TextField(blank=True)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_requested_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_after_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('table_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_meta', to='proprietaire.order')),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_client_payments', to='proprietaire.pilotprofile')),
                ('repeat_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_repeats', to='proprietaire.order')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bar_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_rating', to='proprietaire.order')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_server_ratings', to='proprietaire.pilotprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
