# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientordermeta',
            name='payment_currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('CDF', 'CDF (FC)')], default='CDF', max_length=3),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
