# Generated by Django 6.0.4 on 2026-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientordermeta_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
