# Generated by Django 6.0.4 on 2026-06-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientordermeta_debt_due_date_and_more'),
        ('proprietaire', '0039_table_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_debt_requests', to='proprietaire.pilotprofile'),
        ),
    ]
