# Generated by Django 6.0.4 on 2026-07-07 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientordermeta_debt_server'),
        ('proprietaire', '0041_bar_order_assignment_mode_table_assigned_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_client_debts', to='proprietaire.pilotprofile'),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_response_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='debt_status',
            field=models.CharField(blank=True, default='NONE', max_length=20),
        ),
    ]
