# Generated by Django 5.2.14 on 2026-08-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientordermeta_debt_handled_at_and_more'),
        ('proprietaire', '0046_mark_existing_paid_orders_stock_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=80)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_metas', to='client.tableparticipant'),
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('OPEN', 'Ouverte'), ('PAID', 'Payée'), ('CLOSED', 'Libérée')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_session', to='proprietaire.facture')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='proprietaire.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='tableparticipant',
            name='table_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='client.tablesession'),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_metas', to='client.tablesession'),
        ),
        migrations.AddConstraint(
            model_name='tableparticipant',
            constraint=models.UniqueConstraint(fields=('table_session', 'session_key'), name='unique_table_session_participant'),
        ),
    ]
