# Generated by Django 5.2.14 on 2026-08-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_tableparticipant_clientordermeta_participant_and_more'),
        ('proprietaire', '0046_mark_existing_paid_orders_stock_deducted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['OPEN', 'PAID'])), fields=('table',), name='unique_active_session_per_table'),
        ),
    ]
