# Generated by Django 5.2.14 on 2026-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_tablesession_unique_active_session_per_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableparticipant',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='order_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
