# Generated by Django 5.2.14 on 2026-08-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_tableparticipant_ready_at_tablesession_order_sent_at'),
        ('proprietaire', '0050_adsenserevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientordermeta',
            name='server_call_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='server_call_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='server_call_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_client_calls', to='proprietaire.pilotprofile'),
        ),
        migrations.AddField(
            model_name='clientordermeta',
            name='server_call_status',
            field=models.CharField(blank=True, default='NONE', max_length=20),
        ),
    ]
