from django.urls import path
from .html_views import (
    DashboardView, EstablishmentSetupView, ProfileSetupView,
    InventoryView, FinanceView, TeamView, TeamRequestActionView, TeamAccessActionView, TablesView, EstablishmentDetailsView, TableSetupView,
    TableActionView, TableDownloadQRView, EstablishmentReadyView, StaffInvitationPDFView,
    RecordLossView, MixedCaseArrivalView, ToggleCurrencyView, FactureActionView, TakeOrderView,
    SwitchEstablishmentView,
    LiveOrdersAPIView, UpdateOrderStatusView, DownloadFacturePDFView, DownloadAllFacturesView, ClientHistoryAPIView, ClientManagementView, NotificationsAPIView, AdvisorAPIView, FCMConfigAPIView, FCMTokenAPIView
)

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard_html'),
    path('setup-bar/', EstablishmentSetupView.as_view(), name='establishment_setup'),
    path('profile-setup/', ProfileSetupView.as_view(), name='profile_setup'),
    path('inventory/', InventoryView.as_view(), name='inventory_html'),
    path('finance/', FinanceView.as_view(), name='finance_html'),
    path('team/', TeamView.as_view(), name='team_html'),
    path('team/request-action/', TeamRequestActionView.as_view(), name='team_request_action'),
    path('team/access-action/', TeamAccessActionView.as_view(), name='team_access_action'),
    path('tables/', TablesView.as_view(), name='tables_html'),
    path('setup-bar/details/', EstablishmentDetailsView.as_view(), name='establishment_details'),
    path('switch-bar/', SwitchEstablishmentView.as_view(), name='switch_establishment'),
    path('setup-bar/tables/', TableSetupView.as_view(), name='table_setup'),
    path('setup-bar/ready/', EstablishmentReadyView.as_view(), name='establishment_ready'),
    path('tables/action/', TableActionView.as_view(), name='table_action'),
    path('tables/download-qr/', TableDownloadQRView.as_view(), name='table_download_qr'),
    path('staff/download-invite/', StaffInvitationPDFView.as_view(), name='staff_download_invite'),
    path('finance/record-loss/', RecordLossView.as_view(), name='record_loss'),
    path('finance/facture-action/', FactureActionView.as_view(), name='facture_action'),
    path('finance/facture/<uuid:facture_id>/pdf/', DownloadFacturePDFView.as_view(), name='download_facture_pdf'),
    path('finance/facture/all/pdf/', DownloadAllFacturesView.as_view(), name='download_all_factures'),
    path('stock/mixed-arrival/', MixedCaseArrivalView.as_view(), name='mixed_case_arrival'),
    path('toggle-currency/', ToggleCurrencyView.as_view(), name='toggle_currency'),
    path('take-order/', TakeOrderView.as_view(), name='take_order'),
    path('api/live-orders/', LiveOrdersAPIView.as_view(), name='api_live_orders'),
    path('api/update-order-status/', UpdateOrderStatusView.as_view(), name='api_update_order_status'),
    path('api/client-history/', ClientHistoryAPIView.as_view(), name='api_client_history'),
    path('clients/', ClientManagementView.as_view(), name='clients_html'),
    path('api/notifications/', NotificationsAPIView.as_view(), name='notifications_api'),
    path('api/advisor/', AdvisorAPIView.as_view(), name='advisor_api'),
    path('api/fcm/config/', FCMConfigAPIView.as_view(), name='fcm_config_api'),
    path('api/fcm/token/', FCMTokenAPIView.as_view(), name='fcm_token_api'),
]
