# Generated by Django 6.0.4 on 2026-04-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaire', '0013_staffshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='serveur_photos/')),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serveurs', to='proprietaire.bar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serveur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
            },
        ),
        migrations.CreateModel(
            name='CommandeServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('table', models.CharField(blank=True, max_length=10)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY', 'Prête'), ('SERVED', 'Servie'), ('PAID', 'Payée')], default='PENDING', max_length=15)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('heure_commande', models.DateTimeField(auto_now_add=True)),
                ('heure_serve', models.DateTimeField(blank=True, null=True)),
                ('heure_paiement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='proprietaire.bar')),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='serveur.serveurprofile')),
            ],
            options={
                'verbose_name': 'Commande serveur',
                'verbose_name_plural': 'Commandes serveurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('BREAK', 'Pause'), ('ENDED', 'Terminé')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='proprietaire.bar')),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='serveur.serveurprofile')),
            ],
            options={
                'verbose_name': 'Quart de travail',
                'verbose_name_plural': 'Quarts de travail',
                'ordering': ['-created_at'],
            },
        ),
    ]
