# Generated by Django 6.0.4 on 2026-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveurprofile',
            name='postnom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
