# Generated by Django 6.0.4 on 2026-04-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0003_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveurprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe'),
        ),
    ]
