# Generated by Django 6.0.4 on 2026-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0004_serveurprofile_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveurprofile',
            name='postnom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
