# Generated by Django 6.0.4 on 2026-06-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0005_allow_blank_postnom'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveurprofile',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmé par le propriétaire'), ('REJECTED', 'Rejeté par le propriétaire')], default='PENDING', max_length=20, verbose_name='Statut de confirmation'),
        ),
    ]
