# Generated by Django 6.0.4 on 2026-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0006_serveurprofile_confirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveurprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
    ]
