# Generated by Django 6.0.4 on 2026-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0007_serveurprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveurprofile',
            name='inventory_access_granted',
            field=models.BooleanField(default=False, verbose_name='Accès inventaire autorisé'),
        ),
        migrations.AddField(
            model_name='serveurprofile',
            name='reports_access_granted',
            field=models.BooleanField(default=False, verbose_name='Accès rapports autorisé'),
        ),
        migrations.AddField(
            model_name='serveurprofile',
            name='tables_access_granted',
            field=models.BooleanField(default=False, verbose_name='Accès tables autorisé'),
        ),
    ]
