# Generated by Django 5.2.9 on 2026-03-26 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du Bar')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse manuelle')),
                ('coordonnees_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordonnées GPS (Auto)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bar_logos/', verbose_name='Logo du Bar')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône Material Symbol", max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, help_text='ex: 33cl, 75cl, 1L', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='master_products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='proprietaire.category')),
            ],
        ),
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnom', models.CharField(blank=True, max_length=150, verbose_name='Postnom')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='pilot_photos/', verbose_name='Photo de Profil')),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietaires', to='proprietaire.bar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.IntegerField(default=0, verbose_name='Nombre de bouteilles en stock')),
                ('seuil_alerte', models.IntegerField(default=12, verbose_name='Alerte stock faible')),
                ('devise', models.CharField(choices=[('USD', '$ (Dollar)'), ('CDF', 'FC (Franc Congolais)')], default='USD', max_length=3)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bouteilles_par_casier', models.IntegerField(blank=True, default=24, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire', to='proprietaire.bar')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaire.masterproduct')),
            ],
            options={
                'unique_together': {('bar', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la Table (ex: Table 12, VIP Lounge)')),
                ('code_qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Flyer QR Code')),
                ('est_active', models.BooleanField(default=True, verbose_name='Table active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='proprietaire.bar')),
            ],
            options={
                'unique_together': {('bar', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='proprietaire.bar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proprietaire.stockitem')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proprietaire.table')),
            ],
        ),
    ]
