# Generated by Django 5.2.9 on 2026-03-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='coordonnees_gps',
        ),
        migrations.AddField(
            model_name='bar',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
    ]
