# Generated by Django 5.2.9 on 2026-03-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0002_remove_bar_coordonnees_gps_bar_google_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='role',
            field=models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('EVENEMENT', 'Responsable Événement'), ('BATIMENT', 'Responsable Bâtiment')], default='PROPRIETAIRE', max_length=20, verbose_name='Rôle Exécutif'),
        ),
    ]
