# Generated by Django 5.2.3 on 2026-03-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0003_pilotprofile_nom_pilotprofile_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='role',
            field=models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('SERVEUR', 'Serveur ou Protocole'), ('EVENEMENT', 'Organisateur d’un événement')], default='PROPRIETAIRE', max_length=20, verbose_name='Rôle Exécutif'),
        ),
    ]
