# Generated by Django 5.2.3 on 2026-03-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0004_alter_pilotprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='role',
            field=models.CharField(choices=[('PROPRIETAIRE', "Propriétaire d'un établissement"), ('SERVEUR', 'Serveur ou Protocole'), ('EVENEMENT', 'Organisateur d’un événement')], default='PROPRIETAIRE', max_length=20, verbose_name='Rôle Exécutif'),
        ),
    ]
