# Generated by Django 5.2.3 on 2026-03-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0005_alter_pilotprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='logo',
        ),
        migrations.AddField(
            model_name='bar',
            name='type_etablissement',
            field=models.CharField(choices=[('BAR', 'Bar'), ('LOUNGE', 'Lounge Bar'), ('CLUB', 'Boîte de nuit'), ('BISTRO', 'Bistro / Restaurant'), ('TERRASSE', 'Terrasse'), ('PUB', 'Pub'), ('EVENT', 'Événement Éphémère')], default='BAR', max_length=20, verbose_name="Type d'établissement"),
        ),
    ]
