# Generated by Django 5.2.3 on 2026-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0006_remove_bar_logo_bar_type_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='code_invitation',
            field=models.CharField(blank=True, help_text='Code unique scanné par les serveurs pour rejoindre cet établissement', max_length=12, unique=True, verbose_name="Code d'invitation QR"),
        ),
    ]
