# Generated by Django 5.2.3 on 2026-04-06 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0007_bar_code_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='code_invitation',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Code d'invitation QR"),
        ),
    ]
