# Generated by Django 6.0.4 on 2026-04-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0008_alter_bar_code_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='prix_achat_casier',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'un casier complet", max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='strategie_gestion',
            field=models.CharField(choices=[('UNITE', "À l'unité (Bouteille)"), ('CASIER', 'Par casier')], default='UNITE', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='bouteilles_par_casier',
            field=models.IntegerField(blank=True, default=24, help_text='Nombre de bouteilles dans un casier', null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de revient par bouteille', max_digits=12),
        ),
    ]
