# Generated by Django 6.0.4 on 2026-04-09 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0009_stockitem_prix_achat_casier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('casiers_achetes', models.IntegerField(default=1)),
                ('bouteilles_par_casier', models.IntegerField(default=24)),
                ('prix_achat_casier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(choices=[('USD', '$ (Dollar)'), ('CDF', 'FC (Franc Congolais)')], default='USD', max_length=3)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='proprietaire.stockitem')),
            ],
        ),
    ]
