# Generated by Django 6.0.4 on 2026-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0010_stocksupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bar_logos/', verbose_name="Logo de l'établissement"),
        ),
    ]
