# Generated by Django 6.0.4 on 2026-04-10 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0011_bar_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('PREPARING', 'En préparation'), ('SERVED', 'Servi'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('date_service', models.DateTimeField(blank=True, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='proprietaire.bar')),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proprietaire.pilotprofile')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='proprietaire.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('statut', models.CharField(choices=[('ORDERED', 'Commandé'), ('SERVED', 'Servi')], default='ORDERED', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proprietaire.order')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proprietaire.stockitem')),
            ],
        ),
    ]
