# Generated by Django 6.0.4 on 2026-04-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0012_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'En service'), ('BREAK', 'En pause'), ('CLOSED', 'Service terminé')], default='ACTIVE', max_length=10)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='proprietaire.bar')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='proprietaire.pilotprofile')),
            ],
        ),
    ]
