# Generated by Django 6.0.4 on 2026-05-08 21:19

import proprietaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0013_staffshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=proprietaire.models.upload_pilot_photo, verbose_name='Photo de Profil'),
        ),
    ]
