# Generated by Django 6.0.4 on 2026-05-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0014_alter_pilotprofile_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('raison', models.CharField(choices=[('CASSE', 'Casse / Dommage'), ('PEREMPTION', 'Péremption'), ('VOL', 'Vol / Disparition'), ('OFFERT', 'Offert / Promo'), ('ERREUR', 'Erreur Inventaire')], default='CASSE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_perte', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertes', to='proprietaire.bar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_pertes', to='proprietaire.stockitem')),
            ],
        ),
    ]
