# Generated by Django 6.0.4 on 2026-05-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0015_perte'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='format_casier',
            field=models.CharField(choices=[('PETIT', 'Petit Format (ex: 30cl, 33cl)'), ('GROS', 'Gros Format (ex: 50cl, 65cl, 72cl)')], default='PETIT', max_length=10, verbose_name='Format du Casier'),
        ),
    ]
