# Generated by Django 6.0.4 on 2026-05-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0016_masterproduct_format_casier'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='volume_cl',
            field=models.IntegerField(default=0, help_text='Volume total en cl (ex: 75, 100)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unite_vente',
            field=models.CharField(choices=[('BOUTEILLE', 'Bouteille'), ('VERRE', 'Verre')], default='BOUTEILLE', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='unite_vente',
            field=models.CharField(choices=[('BOUTEILLE', 'Bouteille'), ('VERRE', 'Verre')], default='BOUTEILLE', max_length=20),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='prix_vente_verre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reduction_bouteille_entiere',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction en % si achat bouteille complète', max_digits=5),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='vente_au_verre',
            field=models.BooleanField(default=False, verbose_name='Activer la vente au verre'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='volume_verre_cl',
            field=models.IntegerField(default=5, help_text='Taille standard du verre en cl (ex: 5, 12, 15)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantite_actuelle',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Bouteilles en stock'),
        ),
        migrations.AlterField(
            model_name='stocksupply',
            name='casiers_achetes',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
