# Generated by Django 6.0.4 on 2026-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0017_masterproduct_volume_cl_orderitem_unite_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='taux_change_usd_to_cdf',
            field=models.DecimalField(decimal_places=2, default=2800.0, max_digits=10, verbose_name='Taux de change (1$ en FC)'),
        ),
    ]
