# Generated by Django 6.0.4 on 2026-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0018_bar_taux_change_usd_to_cdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('CDF', 'CDF (FC)')], default='USD', max_length=3),
        ),
    ]
