# Generated by Django 6.0.4 on 2026-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0019_pilotprofile_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='abonnement_expire_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration de l'abonnement"),
        ),
    ]
