# Generated by Django 6.0.4 on 2026-05-16 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0020_bar_abonnement_expire_le'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de Facture')),
                ('client_fournisseur', models.CharField(max_length=255, verbose_name='Nom du Client / Fournisseur')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_cdf', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('type_facture', models.CharField(choices=[('CLIENT', 'Dette Client'), ('FOURNISSEUR', 'Dépense Fournisseur')], default='CLIENT', max_length=20)),
                ('statut', models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée')], default='IMPAYEE', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='proprietaire.bar')),
            ],
        ),
    ]
