# Generated by Django 6.0.4 on 2026-05-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0021_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du Client'),
        ),
    ]
