# Generated by Django 6.0.4 on 2026-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0022_order_client_name_order_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='factures', to='proprietaire.order'),
        ),
    ]
