# Generated by Django 6.0.4 on 2026-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0023_facture_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='garant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Garant / Caution'),
        ),
    ]
