# Generated by Django 6.0.4 on 2026-05-17 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0024_facture_garant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='garant',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('dette_autorisee', models.BooleanField(default=False, verbose_name='Autorisé explicitement à la dette')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='proprietaire.bar')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
    ]
