# Generated by Django 6.0.4 on 2026-05-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0025_remove_facture_garant_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='seuil_dette_cdf',
            field=models.PositiveIntegerField(default=100000, verbose_name="Seuil d'éligibilité à la dette (FC)"),
        ),
    ]
