# Generated by Django 6.0.4 on 2026-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0026_bar_seuil_dette_cdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='seuil_dette_cdf',
        ),
        migrations.AddField(
            model_name='bar',
            name='seuil_dette_eligible',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name="Seuil d'éligibilité pour dette (FC)"),
        ),
    ]
