# Generated by Django 6.0.4 on 2026-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0027_remove_bar_seuil_dette_cdf_bar_seuil_dette_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('PROPRIETAIRE', "Propriétaire d'un établissement"), ('SERVEUR', 'Serveur ou Protocole'), ('EVENEMENT', 'Organisateur d’un événement')], max_length=20, null=True, verbose_name='Rôle Exécutif'),
        ),
    ]
