# Generated by Django 6.0.4 on 2026-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0033_fcmdevicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('PREPARING', 'En préparation'), ('SERVED', 'Servi'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
    ]
