# Generated by Django 6.0.4 on 2026-06-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0034_alter_order_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='prix_mensuel_par_table_usd',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=12, verbose_name='Prix mensuel par table (USD)'),
        ),
    ]
