# Generated by Django 6.0.4 on 2026-06-17 01:20

from django.db import migrations, models


def backfill_owned_bars(apps, schema_editor):
    PilotProfile = apps.get_model('proprietaire', 'PilotProfile')
    for profile in PilotProfile.objects.select_related('bar').all():
        if profile.bar_id:
            profile.owned_bars.add(profile.bar_id)


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0035_bar_prix_mensuel_par_table_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='owned_bars',
            field=models.ManyToManyField(blank=True, related_name='owners', to='proprietaire.bar', verbose_name='Etablissements possedes'),
        ),
        migrations.RunPython(backfill_owned_bars, migrations.RunPython.noop),
    ]
