# Generated by Django 6.0.4 on 2026-06-17 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_trial_consumed_at(apps, schema_editor):
    PilotProfile = apps.get_model('proprietaire', 'PilotProfile')
    for profile in PilotProfile.objects.select_related('bar').all():
        if profile.bar_id and profile.trial_consumed_at is None:
            profile.trial_consumed_at = profile.bar.date_creation
            profile.save(update_fields=['trial_consumed_at'])



class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0036_pilotprofile_owned_bars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='trial_consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Essai gratuit consommé le'),
        ),
        migrations.CreateModel(
            name='OwnerAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BAR_CREATED', 'Bar créé'), ('TRIAL_GRANTED', 'Essai accordé'), ('TRIAL_DENIED', 'Essai refusé'), ('BAR_SWITCHED', 'Bar basculé')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='proprietaire.bar')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='proprietaire.pilotprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='owner_audit_event_idx'), models.Index(fields=['bar', '-created_at'], name='owner_audit_bar_idx'), models.Index(fields=['profile', '-created_at'], name='owner_audit_profile_idx')],
            },
        ),
        migrations.RunPython(backfill_trial_consumed_at, migrations.RunPython.noop),
    ]
