# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0037_pilotprofile_trial_consumed_at_owneraccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarAdvisorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_enabled', models.BooleanField(default=True, verbose_name='Conseiller propriétaire actif')),
                ('server_enabled', models.BooleanField(default=True, verbose_name='Conseiller serveur actif')),
                ('provider', models.CharField(choices=[('local', 'Local'), ('gemini', 'Gemini'), ('openai', 'OpenAI'), ('auto', 'Auto')], default='local', max_length=20, verbose_name='Moteur de réponse')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_settings', to='proprietaire.bar')),
            ],
            options={
                'verbose_name': 'Réglage du conseiller IA',
                'verbose_name_plural': 'Réglages des conseillers IA',
            },
        ),
    ]
