# Generated by Django 6.0.4 on 2026-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0038_baradvisorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expiration d'abonnement"),
        ),
        migrations.AddField(
            model_name='table',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Début d'abonnement"),
        ),
    ]
