# Generated by Django 6.0.4 on 2026-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0039_table_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=20),
        ),
    ]
