# Generated by Django 6.0.4 on 2026-07-04 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0040_alter_facture_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='order_assignment_mode',
            field=models.CharField(choices=[('AUTO', 'Automatique vers les serveurs disponibles'), ('TABLE', 'Selon le serveur assigné à la table')], default='AUTO', max_length=10, verbose_name='Mode attribution commandes'),
        ),
        migrations.AddField(
            model_name='table',
            name='assigned_server',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SERVEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='proprietaire.pilotprofile', verbose_name='Serveur assigné'),
        ),
    ]
