# Generated by Django 5.2.14 on 2026-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0041_bar_order_assignment_mode_table_assigned_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
