# Generated by Codex on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0042_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='mobile_money_airtel',
            field=models.CharField(blank=True, max_length=32, verbose_name='Airtel Money'),
        ),
        migrations.AddField(
            model_name='bar',
            name='mobile_money_mpesa',
            field=models.CharField(blank=True, max_length=32, verbose_name='M-Pesa'),
        ),
        migrations.AddField(
            model_name='bar',
            name='mobile_money_orange',
            field=models.CharField(blank=True, max_length=32, verbose_name='Orange Money'),
        ),
    ]
