# Generated by Django 5.2.14 on 2026-08-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0043_bar_mobile_money_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stock déduit le'),
        ),
    ]
