# Generated by Django 5.2.14 on 2026-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0044_order_stock_deducted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deduire_stock',
            field=models.BooleanField(default=True, verbose_name='Déduire du stock'),
        ),
    ]
