# Generated by Django 5.2.14 on 2026-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0046_mark_existing_paid_orders_stock_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'En attente du groupe'), ('PENDING', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('PREPARING', 'En préparation'), ('SERVED', 'Servi'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
    ]
