# Generated by Django 5.2.14 on 2026-08-17 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0047_alter_order_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tables')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant USD')),
                ('period_days', models.PositiveIntegerField(default=30, verbose_name='Durée (jours)')),
                ('period_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='proprietaire.bar')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_subscription_payments', to='proprietaire.pilotprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
