# Generated by Django 5.2.14 on 2026-08-17 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0048_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Titre de la dépense')),
                ('category', models.CharField(choices=[('API', 'API et services en ligne'), ('VPS', 'VPS / hébergement'), ('MARKETING', 'Marketing'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant USD')),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de la dépense')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense d’administration',
                'verbose_name_plural': 'Dépenses d’administration',
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
    ]
