# Generated by Django 5.2.14 on 2026-08-17 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0049_administrationexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsenseRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Période')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gains USD')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adsense_revenues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gain Google AdSense',
                'verbose_name_plural': 'Gains Google AdSense',
                'ordering': ['-period', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('period',), name='unique_adsense_revenue_period')],
            },
        ),
    ]
